sudo: required

services:
  - docker

language: go

go:
  - 1.6

before_install:
  - sudo apt-get update
  - sudo apt-get install -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
  - nvm install 5.9
  - nvm use 5.9

before_script:
  - uname -a
  - docker version
  - go version
  - npm version

script:
  - make setup
  - make
  - make test

after_success:
  - |
    [ "$TRAVIS_BRANCH" != "master" ] || docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - |
    [ "$TRAVIS_BRANCH" != "master" ] || make docker-deploy

notifications:
  email:
    - agilestack-dev@agilestack.io
